services:
  fastapi:
    build:
      context: ${VPS_DIRECTORY_AIDWISE_DEMO}  # Use this directory as the context
    ports:
      - "${VPS_EXPOSED_PORT_AIDWISE_DEMO}:8000"
    env_file:
      - .env
    volumes:
      - ${VPS_DIRECTORY_AIDWISE_DEMO}:/app  # Mount this directory
    command: uvicorn app:app --host 0.0.0.0 --port 8000